### ISSUE TITLE
Change the shortcut to something that you do not accidentally hit while using an application

### ISSUE THREAD

**Issue by Artur-** [vaadin/copilot#10]
When you type a lot of special characters or capital characters you might very well end up pressing shift twice. Then copilot pops up and BAM, it is in the way. 

The shortcut should be such that you do not accidentally ever trigger it during application testing

**Comment by probert94** [comment]
Another problem related to this is that if you keep pressing `shift` it keeps toggling the copilot. So the `repeat` flag is probably ignored.

**Comment by TatuLund** [comment]
Good example is Selection Grid where shift + space is used for toggling multi selection, also shift + mouse click

https://vaadin.com/directory/component/selection-grid

**Comment by TatuLund** [comment]
As almost any key combo can conflict with the application, there should be way to configure it.

**Comment by Artur-** [comment]
> shift + space is used for toggling multi selection

This does not activate copilot though

> shift + mouse click

This seems to be an oversight when a click in between does not abort activation

**Comment by finaris-cs** [comment]
Maybe there is a setting to switch off vaadin copilot? The accidental triggering when writing capital letters is a bit annoying.

**Comment by Artur-** [comment]
We made the following changes:
1. Change the activation shortcut to shift+(ctrl+ctrl) or shift+(cmd+cmd)
2. Added a `vaadin.copilot.enable` property you can set to `false` to prevent copilot from showing up
3. Removed copilot from 24.3.5 to avoid issues. It will be in 24.4
4. Added a possibility to disable the shortcut
