### ISSUE TITLE
[FEATURE] Edit functionality for Flow views

### ISSUE THREAD

**Issue by Artur-** [vaadin/copilot#17]
### Describe the solution you'd like

All the edit functionality available when you edit Hilla views should be available also when using Flow. Currently this is:
1. Dragging from the component palette
2. Drag'n'drop in the UI
3. Delete component
4. Duplicate component
5. Wrap-with
6. AI prompt

**Comment by MarcinVaadin** [comment]
Initial version done behind the feature flag
