### ISSUE TITLE
[BUG] Flow routes show multiple times in the route panel

### ISSUE THREAD

**Issue by jojule** [vaadin/copilot#18]
### Description of the Bug

Flow routes show multiple times in the route panel.

### Expected Behavior

A description of what you would expect to happen. (Sometimes it is clear what the expected outcome is if something does not work; other times, it is not super clear.)

### Minimal Reproducible Example

- Create a new project at start.vaadin.com
- Add one empty hilla and one empty flow view
- Run the project
- Observe the flow routes being duplicated in the routes panel (number of duplications seem to vary, I see the same route four times)

<img width="502" alt="Screenshot 2024-04-25 at 11 18 53 AM" src="https://github.com/vaadin/copilot/assets/644969/35e1e815-1341-4f06-9c56-9230b9450a49">

### Versions

- Hilla: 24.4.0.alpha25
- Flow: 24.4.0.alpha31
- Vaadin: 24.4.0.alpha24
- Copilot: 24.4.0.alpha24
- Copilot IDE Plugin: 1.0.5-intellij
- Java: JetBrains s.r.o. 21.0.2
- Java Hotswap: false
- Frontend Hotswap: Enabled, using Vite
- OS: aarch64 Mac OS X 14.4.1
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by Artur-** [comment]
This was fixed after the alpha24 release
