### ISSUE TITLE
Undo does not work when copy & pasting Figma design components into a Flow view

### ISSUE THREAD

**Issue by vesanieminen** [vaadin/copilot#22]
### Description of the Bug

Copy & pasting a simple component into a Flow view and pressing undo in the browser does not work. The component copy & paste works ok but undo does not do anything.

### Expected Behavior

Undo should work the same way as it does via the IDE.

### Minimal Reproducible Example

Create a new project that has an empty view in start.vaadin.com. Enable the feature flags for Flow support and Figma copy & paste:

```
# Support for editing Flow views with Copilot
com.vaadin.experimental.copilotFlow=true
# Copilot experimental features
com.vaadin.experimental.copilotExperimentalFeatures=true
```

### Versions

- Vaadin Flow/Hilla Framework Version: e.g., 24.4.3
- Copilot Version: 24.4.3.
- Browser Information: Chrome 126.0.6478.115
- IDE: IntelliJ IDEA 2023.3.7 (Ultimate Edition)

**Comment by Artur-** [comment]
Fixed in the latest version
