### ISSUE TITLE
[BUG] Figma -> Flow copypaste is not working for Radiobuttongroup 

### ISSUE THREAD

**Issue by vesanieminen** [vaadin/copilot#24]
### Description of the Bug

Copy & pasting a Figma design to Flow does not work for a radio button group component from the official Vaadin Figma design Assets palette.

### Expected Behavior

It should work 🙂

### Minimal Reproducible Example

Example Figma design here: https://www.figma.com/design/d8c6aRtLWWLwdzs0zdQcwJ/Vaadin-Design-System-(Community)---Vesa-test?node-id=9705-4408&t=crdlMdEv3Yf604zO-0

### Versions

Hilla: 24.4.1
Flow: 24.4.2
Vaadin: 24.4.3
Copilot: 24.4.3
Copilot IDE Plugin: 1.0.9-intellij
Java: Oracle Corporation 17.0.10
Java Hotswap: true
Frontend Hotswap: Disabled, using pre-built bundle
OS: aarch64 Mac OS X 14.3
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by Artur-** [comment]
Fixed in the latest version
