### ISSUE TITLE
[BUG] Copilot IDE Plugin not detected

### ISSUE THREAD

**Issue by bwajtr** [vaadin/copilot#29]
### Description of the Bug

1. Using IntelliJ IDEA 2024.1.4 (Ultimate Edition)
2. Installed Vaadin plugin (version 1.0.9)
3. Restarted IDEA to activate the plugin
<img width="400" alt="image" src="https://github.com/user-attachments/assets/d7e630a6-d150-4356-8cec-8a9c2826a037">

4. Started a Sprint Boot application from within Idea (using Run configuration where I'm running directly the ApplicadtionMain class)
5. Started copilot
6. Copilot reports that IDE plugin is not installed
<img width="351" alt="image" src="https://github.com/user-attachments/assets/24eac5fa-6910-4deb-aad5-e11aab622247">

### Expected Behavior

I'd expect that the plugin is detected

### Versions
IntelliJ Idea: IntelliJ IDEA 2024.1.4 (Ultimate Edition)
Hilla: 24.4.4
Flow: 24.4.4
Vaadin: 24.4.7
Copilot: 24.4.8
Copilot IDE Plugin: false
Java: Eclipse Adoptium 17.0.7
Java Hotswap: false
Frontend Hotswap: Disabled, using pre-built bundle
OS: aarch64 Mac OS X 14.5
Browser: Mozilla/5.0 (Macintosh

**Comment by MarcinVaadin** [comment]
Are you using multimodule application that do not have com.vaadin dependency in root pom.xml?

**Comment by bwajtr** [comment]
@MarcinVaadin Yes, the project is a multimodule application, with the following structure:

<img width="736" alt="image" src="https://github.com/user-attachments/assets/fc7afa26-0a6c-4516-90da-f2c7fc10f28f">

**Comment by MarcinVaadin** [comment]
It's an issue with plugin itself, will be covered within https://github.com/vaadin/intellij-plugin/issues/33

**Comment by Artur-** [comment]
Was this fixed by https://github.com/vaadin/intellij-plugin/pull/82 ?

**Comment by MarcinVaadin** [comment]
Yes
