### ISSUE TITLE
Copilot Routes Go to source not working

### ISSUE THREAD

**Issue by DarioViva42** [vaadin/copilot#32]
### Description of the bug

When I use copilot to see a listing of all routes this is what I see:

![image](https://github.com/user-attachments/assets/75d5ebeb-5183-4590-8a8c-fd686d59b69a)

Pretty useful, but when i click on the marked buttons nothing happens.

### Expected behavior

Clicking on these buttons should navigate to the source of the view.

### Minimal reproducible example

https://github.com/DarioViva42/vaadinHistoryBug/tree/latest

This project was created for another issue, but it can also demonstrate this issue.

### Versions

- Vaadin / Flow version: 24.4.11 / Flow 24.4.7
- Java version: 21
- OS version: Sonoma 14.5

**Comment by Artur-** [comment]
What IDE are you running?

**Comment by DarioViva42** [comment]
> What IDE are you running?

Very good question. `IntelliJ IDEA 2024.2.1 (Ultimate Edition)`
And more detailed: `Build #IU-242.21829.142, built on August 28, 2024`

**Comment by Artur-** [comment]
Any error logs in the browser or in the server output? Because it seems to work fine for me

https://github.com/user-attachments/assets/586c5677-59dc-4fef-b238-ac583680f044

Do you have the Vaadin IntellIiJ plugin installed?

**Comment by DarioViva42** [comment]
I see no server logs, no copilot logs and no browser logs.

Here are more details:
![image](https://github.com/user-attachments/assets/054075b1-e560-414b-8af6-eca0e4e4f9ba)

I have two Vaadin Plugins:
![image](https://github.com/user-attachments/assets/341e4a73-d2dd-49e7-b185-7f1aa20e083e)

The Go to Source for components is working fine
![image](https://github.com/user-attachments/assets/f5ebde84-ba5c-4bf2-bdb5-a56b82ae70f3)

**Comment by MarcinVaadin** [comment]
Issue found and fixed in Copilot, will be delivered in next release (24.4.13), thank you for submitting!
