### ISSUE TITLE
Copilot Routes Navigation not working

### ISSUE THREAD

**Issue by DarioViva42** [vaadin/copilot#33]
### Description of the Bug

When I use copilot to see a listing of all routes this is what I see:
![image](https://github.com/user-attachments/assets/5ca2ce17-dcd2-4fe0-9357-869dbc6aaaa4)

Now, clicking on the marked links does navigate to the correct view. this is a helpful feature. but when configuring `vaadin.url-mapping` to not use the root for vaadin routes this no longer works. the copilot still navigates to the routes as if `vaadin.url-mapping` is not set. 
Also hovering over the links, normally showing the url of the link, does not show the expected url.
![image](https://github.com/user-attachments/assets/4f356d22-086a-4c07-ab79-d078ea9cbc1e)

In the demonstration project I use `/vaadin/*` as the mapping.
```properties
vaadin.url-mapping=/vaadin/*
```

### Expected Behavior

I would expect copilot to honor the mapping. Also I expect to see `localhost:8080/vaadin/hello-world` instead of `localhost:8080/vaadin/` when hovering over the link.

### Minimal Reproducible Example

https://github.com/DarioViva42/vaadinHistoryBug/tree/navigation

The repo was used as a demonstration for another issue, but branch `navigation` can be used to demonstrate this issue.

### Versions

- Vaadin Flow Framework Version: 24.4.7
- Copilot Version: 24.4.12
- Browser Information: Firefox 129.0.2

**Comment by DarioViva42** [comment]
@czp13 when will the fix be shipped?

**Comment by Artur-** [comment]
It will be in the next release

**Comment by czp13** [comment]
@DarioViva42 It was just autoclosed because the above PR was merged.

As Artur said in next release this shall be fixed, and releases are quite frequent if you check these:
- https://github.com/vaadin/copilot/releases

So hopefully soon you can test it!

**Comment by DarioViva42** [comment]
@czp13 
> […] because the above PR was merged.

I don't see the PR. Copilot is closed source as far as I know, so I can not see what changes you committed.
But good to hear its fixed that quickly.

**Comment by czp13** [comment]
> I don't see the PR. Copilot is closed source as far as I know, so I can not see what changes you committed. But good to hear its fixed that quickly.
Oh, okey, I thought at least some kind of info about a PR that was merged is visible in the issue ticket. Yes, Copilot is closed source. 

Glad to hear, take care.
