### ISSUE TITLE
[BUG] Inconsistent naming for Hotswap agent in VS Code

### ISSUE THREAD

**Issue by Legioth** [vaadin/copilot#39]
### Description of the Bug

The text in the Development Workflow dialog instructs using a "Debug using Hotswap Agent" configuration but the created configuration is named "Launch using Hotswap Agent".

### Expected Behavior

Consistency

### Minimal Reproducible Example

1. Launch using VS Code
2. Open the Development Workflow dialog and click the link to install Hotswap agent

### Versions

- Vaadin 24.5.0.beta5
  - Copilot 24.5.0.beta4
- VS Code 1.94.0
  - Vaadin extension 1.0.7

**Comment by MarcinVaadin** [comment]
And also we must unify if it's `HotswapAgent` `HotSwap Agent` or `HotSwapAgent`.

<img width="892" alt="image" src="https://github.com/user-attachments/assets/cbd41f54-33f0-44d6-a713-33d5df5e9d75">

<img width="192" alt="image" src="https://github.com/user-attachments/assets/24d69e31-a8ec-4c11-a9c5-ae0bb9bc1ac7">

<img width="192" alt="image" src="https://github.com/user-attachments/assets/e6e498e1-6e61-4da6-87fe-532a86aa21e4">

<img width="192" alt="image" src="https://github.com/user-attachments/assets/040895cb-5a13-4c01-801d-839897761fe4">


Hard to tell from hotswap webpage, they use also different naming everywhere 😃

**Comment by Legioth** [comment]
Sure, but that's less confusing than "Debug" vs "Launch".
