### ISSUE TITLE
[BUG] Cannot access the activation button menu on a view using the login overlay

### ISSUE THREAD

**Issue by Legioth** [vaadin/copilot#45]
### Description of the Bug

On a Hilla view with a `<LoginOverlay>`, you cannot interact with the activation button menu. The menu does open when you move the mouse over the button but it closes immediately when you move the cursor out from the actual button.

Furthermore, if you move the button by dragging it, then the menu no longer opens when you hover the button until you reload the page.

### Expected Behavior

Expected that the activation button menu works the same regardless of whether a view uses login overlay

### Minimal Reproducible Example

Application from start.vaadin.com with access control for the default route and a Hilla main layout

### Versions

- Vaadin Flow/Hilla Framework Version: 24.5.2
- Copilot Version: 24.5.2
- Browser Information: Tested with Chrome 130.0.6723.70 and Firefox 130.0.1 on Mac

**Comment by Artur-** [comment]
This seems to have been fixed in the latest version
