### ISSUE TITLE
[BUG] Log does not work with long messages

### ISSUE THREAD

**Issue by Legioth** [vaadin/copilot#47]
### Description of the Bug

Long error messages are not wrapped to multiple lines so that the entire message could be read without having a screen that is 10000 pixels wide.

<img width="1250" alt="Screenshot 2024-10-31 at 15 40 46" src="https://github.com/user-attachments/assets/ce7f5c8d-95a6-4807-a54c-db02bbaa6e92">

### Expected Behavior

Expected the text to wrap.

### Minimal Reproducible Example

1. Add a `<Button onClick={()=> console.error("Hello ".repeat(200)+ "world")} >Log long error</Button>` to a Hilla view
2. Click the button
3. Open the Log panel in Copilot and click on the message summary.

### Versions

- Vaadin Flow/Hilla Framework Version: 24.5.2
- Copilot Version: 24.5.2

**Comment by MarcinVaadin** [comment]
Issue already fixed, will be available in 24.5.3.
