### ISSUE TITLE
[BUG] Full page reload not working with HotswapAgent anymore

### ISSUE THREAD

**Issue by sveinnetnordic** [vaadin/copilot#49]
### Cannot do a full page reload with HotswapAgent 2.0.1
Most of the time I use a full page reload to run constructor/onAttach. HotswapAgent 2.0.1 works best with Copilot.

Now I have a full copy of my java folder with different ...\lib\hotswap\hotswap-agent.jar
C:\ProgramFiles\Java\jbr_jcef-21.0.3-windows-x64-b509.11+hotswap-agent-1.4.2.
C:\ProgramFiles\Java\jbr_jcef-21.0.3-windows-x64-b509.11+hotswap-agent-2.0.1.

I find me using 1.4.2 most of the time. I need to switch Project SDK and restart to switch HotswapAgent 

https://vaadin.com/docs/latest/flow/configuration/live-reload/hotswap-agent#efficiency
Could not find this option, but the option should be to toggle between full reload/partial reload, and maybe also set it off (last is not needed for me.) 

### Expected Behavior
A full page reload should be default / an option to toggle is missing

### Minimal Reproducible Example

Use HotswapAgent 1.4.2 for a full page
Use HotswapAgent 2.0.1 for a partial reload / refresh

### Versions

Hilla: 24.5.4
Flow: 24.5.4
Vaadin: 24.5.4
Copilot: 24.5.4
Frontend Hotswap: Disabled, using pre-built bundle
OS: amd64 Windows 11 10.0
Java: JetBrains s.r.o. 21.0.3
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Java Hotswap: Hotswap is partially enabled
IDE Plugin: Not installed (it is installed, but not detected)

**Comment by Artur-** [comment]
If I understand this correctly, you want a full page reload to happen automatically and it does not. Why do you want a full page reload to happen?

**Comment by sveinnetnordic** [comment]
> If I understand this correctly, you want a full page reload to happen automatically and it does not. Why do you want a full page reload to happen?

Just now I am opening a Dialog in onAttach, with fresh data. Will work with it for days... In the end it will be a button. 2.0.1 will not open the dialog

**Comment by sveinnetnordic** [comment]
This is for Flow development (vaadin.frontend.hotdeploy=false, dev.bundle)

**Comment by sveinnetnordic** [comment]
Correction: With 2.0.1 init/constructor and onAttach is runnig, but the Dialog will not open

**Comment by Artur-** [comment]
Created this Flow issue https://github.com/vaadin/flow/issues/20473

**Comment by Artur-** [comment]
The dialog fix was shipped in Vaadin 24.5.7

**Comment by sveinnetnordic** [comment]
Now the dialog opens, but it reloads many times, or forever. Created a minimal sample:
![image](https://github.com/user-attachments/assets/938a5759-ced9-4910-a291-9581f2f54b0b)

![image](https://github.com/user-attachments/assets/32f969c2-092e-4009-8114-73eda0bb191e)

**Comment by sveinnetnordic** [comment]
BTW: The page use to load two times in the latest previous releases on hotswap

**Comment by sveinnetnordic** [comment]
Tried once more, when opening a dialog, after page load - a new page refresh is done and the dialog is closed. Not usable!
